import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import './style.css';
const scene=new T.Scene();scene.background=new T.Color('#100d19');scene.fog=new T.FogExp2('#100d19',.026);
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;document.querySelector('#scene').appendChild(renderer.domElement);
const camera=new T.PerspectiveCamera(36,innerWidth/innerHeight,.1,100);camera.position.set(8,6.1,11.5);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,2.35,0);controls.enableDamping=true;controls.minDistance=6;controls.maxDistance=19;controls.maxPolarAngle=Math.PI*.49;controls.minPolarAngle=.4;
const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;
const ambient=new T.HemisphereLight(0xc4c5ff,0x492713,1.3);scene.add(ambient);const key=new T.SpotLight(0xffe0aa,130,30,.6,.7,1.3);key.position.set(4,9,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.bias=-.0001;scene.add(key);const rim=new T.DirectionalLight(0x9896ff,2);rim.position.set(-5,5,-4);scene.add(rim);
const gold=new T.MeshStandardMaterial({color:0xc9a45b,metalness:.85,roughness:.25});const ivory=new T.MeshStandardMaterial({color:0xf2e4ca,metalness:.12,roughness:.31});const teal=new T.MeshStandardMaterial({color:0x234b50,metalness:.42,roughness:.3});const plum=new T.MeshStandardMaterial({color:0x452636,metalness:.3,roughness:.36});const bulb=new T.MeshStandardMaterial({color:0xffdf9a,emissive:0xffbe57,emissiveIntensity:3});
const root=new T.Group();scene.add(root);function mesh(g,m,p,parent=root){const o=new T.Mesh(g,m);o.position.set(...p);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}function cyl(r1,r2,h,y,m=gold,parent=root){return mesh(new T.CylinderGeometry(r1,r2,h,96),m,[0,y,0],parent)}function ring(r,y,t=.025,m=gold,parent=root){const o=mesh(new T.TorusGeometry(r,t,10,128),m,[0,y,0],parent);o.rotation.x=Math.PI/2;return o}function sphere(x,y,z,r,m=gold,parent=root){return mesh(new T.SphereGeometry(r,16,12),m,[x,y,z],parent)}
mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:0x15111c,roughness:.36,metalness:.3}),[0,-.08,0],scene).rotation.x=-Math.PI/2;
cyl(2.1,2.02,.15,.08);cyl(2.04,2.04,.28,.28,teal);cyl(2.14,2.1,.1,.47);cyl(2.08,2.08,.11,.56,ivory);[.13,.43,.62].forEach(y=>ring(2.08,y));ring(1.9,.63,.015);ring(1.65,.63,.012);
for(let i=0;i<32;i++){const a=i/32*Math.PI*2;const o=sphere(Math.sin(a)*2.055,.28,Math.cos(a)*2.055,.072);o.scale.set(1,1.4,.3);o.rotation.y=a;sphere(Math.sin(a)*2.05,.55,Math.cos(a)*2.05,.022,bulb)}
cyl(.43,.58,.26,.79);cyl(.29,.37,3.45,2.63,ivory);[1,1.2,2.0,2.08,3.1,3.18,4.18,4.3].forEach(y=>ring(y<1.3?.38:.31,y,.03));
for(let i=0;i<8;i++){const a=i*Math.PI/4;const pts=[];for(let j=0;j<=80;j++){const y=1+j/80*3.2;pts.push(new T.Vector3(.32*Math.sin(a+y*2.2),y,.32*Math.cos(a+y*2.2)))}mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts),80,.013,6,false),gold,[0,0,0]);}
cyl(2.12,2.12,.22,4.55,ivory);ring(2.13,4.44,.045);ring(2.13,4.68,.045);cyl(.12,2.08,.82,5.08,teal);sphere(0,5.63,0,.13);cyl(.025,.075,.28,5.8);sphere(0,5.96,0,.035,bulb);
for(let i=0;i<16;i++){const a=i/16*Math.PI*2;const pts=[new T.Vector3(.14*Math.sin(a),5.5,.14*Math.cos(a)),new T.Vector3(1.1*Math.sin(a),5.13,1.1*Math.cos(a)),new T.Vector3(2.1*Math.sin(a),4.68,2.1*Math.cos(a))];mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts),20,.022,6,false),gold,[0,0,0]);const deco=new T.Group();deco.position.set(Math.sin(a)*2.12,4.55,Math.cos(a)*2.12);deco.rotation.y=a;root.add(deco);const oval=mesh(new T.SphereGeometry(1,16,12),gold,[0,0,.018],deco);oval.scale.set(.072,.085,.018);sphere(0,0,.043,.035,plum,deco);sphere(Math.sin(a)*2.09,4.4,Math.cos(a)*2.09,.04,bulb)}
const glow=new T.PointLight(0xffc477,12,9,2);glow.position.y=3.8;root.add(glow);
// 手工雕塑式木马，统一的陶瓷与黄铜材质。
for(let i=0;i<4;i++){const a=i*Math.PI/2+.3;const horse=new T.Group();horse.position.set(Math.sin(a)*1.3,.99,Math.cos(a)*1.3);horse.rotation.y=a+Math.PI/2;root.add(horse);function ell(x,y,z,sx,sy,sz,m=ivory){const o=sphere(x,y,z,1,m,horse);o.scale.set(sx,sy,sz);return o}ell(0,.28,0,.34,.2,.16);ell(.23,.48,0,.12,.29,.13).rotation.z=-.35;ell(.34,.7,0,.21,.11,.115);ell(.22,.85,-.065,.04,.11,.03);ell(.22,.85,.065,.04,.11,.03);ell(.39,.74,.105,.018,.018,.009,plum);ell(.39,.74,-.105,.018,.018,.009,plum);ell(-.06,.46,0,.21,.035,.18,plum);for(const z of [-.12,.12])for(const x of [-.22,.22]){ell(x,.06,z,.047,.22,.045);ell(x+.035,-.13,z,.065,.045,.052,gold)}const mane=ell(.14,.56,0,.065,.27,.145,gold);mane.rotation.z=-.4;ell(-.37,.15,0,.06,.26,.065,gold).rotation.z=-.5;mesh(new T.CylinderGeometry(.015,.015,3.73,12),gold,[0,1.57,0],horse);}
const names=['1d426ae7844f039618506f7b94a2167b.JPG','3f3cad8c1f08c1719ae14f335973a7c0.JPG','8997f31a8b1055445d02dde4ed575489.JPG','IMG_1713.JPG','IMG_3719.JPG','faceu_1777784805810.JPG'];const photos=[],clickables=[];const loader=new T.TextureLoader();let ready=0;
function addPhoto(url,i,total=12){const a=i/total*Math.PI*2;const pivot=new T.Group();pivot.position.set(Math.sin(a)*1.91,4.4,Math.cos(a)*1.91);pivot.rotation.y=a;root.add(pivot);const drop=.55+(i%3)*.4;mesh(new T.CylinderGeometry(.009,.009,drop,8),gold,[0,-drop/2,0],pivot);const frame=new T.Group();frame.position.y=-drop-.49;pivot.add(frame);mesh(new T.BoxGeometry(.7,.96,.035),ivory,[0,0,0],frame);mesh(new T.BoxGeometry(.724,.985,.018),gold,[0,0,-.018],frame);const tex=loader.load(url,()=>{ready++;if(ready>=12)document.querySelector('#loading').hidden=true});tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=renderer.capabilities.getMaxAnisotropy();const plane=mesh(new T.PlaneGeometry(.6,.76),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}),[0,.055,.022],frame);plane.userData.url=url;clickables.push(plane);sphere(0,-drop-.99,0,.038,gold,pivot);photos.push({pivot,frame,a});}
for(let i=0;i<12;i++)addPhoto(import.meta.env.BASE_URL+'photos/'+names[i%names.length],i);
const dustGeo=new T.BufferGeometry(),coords=[];for(let i=0;i<240;i++)coords.push((Math.random()-.5)*14,Math.random()*8,(Math.random()-.5)*12);dustGeo.setAttribute('position',new T.Float32BufferAttribute(coords,3));const dust=new T.Points(dustGeo,new T.PointsMaterial({color:0xe7c489,size:.018,transparent:true,opacity:.65}));scene.add(dust);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.3,.4,.85);composer.addPass(bloom);composer.addPass(new OutputPass());
let spinning=true,wind=false,lit=true;document.querySelector('#rotate').onclick=e=>{spinning=!spinning;e.target.textContent=spinning?'暂停旋转':'开始旋转'};document.querySelector('#wind').onclick=e=>{wind=!wind;e.target.setAttribute('aria-pressed',wind)};document.querySelector('#light').onclick=e=>{lit=!lit;glow.intensity=lit?12:0;bulb.emissiveIntensity=lit?3:0;key.intensity=lit?130:35;e.target.textContent=lit?'熄灯':'点灯';e.target.setAttribute('aria-pressed',lit)};document.querySelector('#reset').onclick=()=>{camera.position.set(8,6.1,11.5);controls.target.set(0,2.35,0);root.rotation.y=0};document.querySelector('#upload').onclick=()=>document.querySelector('#files').click();document.querySelector('#files').onchange=e=>{[...e.target.files].slice(0,12).forEach((f,i)=>addPhoto(URL.createObjectURL(f),i,Math.min(e.target.files.length,12)))};document.querySelector('#shot').onclick=()=>{composer.render();const a=document.createElement('a');a.download='流光-记忆.png';a.href=renderer.domElement.toDataURL('image/png');a.click()};const dialog=document.querySelector('#viewer');document.querySelector('#close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
const ray=new T.Raycaster();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hit=ray.intersectObjects(clickables)[0];if(hit){dialog.querySelector('img').src=hit.object.userData.url;dialog.showModal()}});
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight)}addEventListener('resize',resize);let last=0;function render(t){const dt=Math.min((t-last)/1000,.05);last=t;if(spinning)root.rotation.y+=dt*.16;for(const p of photos)p.pivot.rotation.z=Math.sin(t*.0017+p.a)*(wind?.13:.018);dust.rotation.y=t*.000012;controls.update();composer.render();requestAnimationFrame(render)}requestAnimationFrame(render);
renderer.toneMappingExposure=.8;scene.environmentIntensity=.55;ambient.intensity=.55;key.intensity=45;rim.intensity=.7;glow.intensity=4;bloom.strength=.18;
function fitViewport(){camera.fov=innerWidth<700?58:36;camera.updateProjectionMatrix()}fitViewport();addEventListener('resize',fitViewport);
document.querySelector('#light').onclick=e=>{lit=!lit;glow.intensity=lit?4:0;bulb.emissiveIntensity=lit?3:0;key.intensity=lit?45:15;e.target.textContent=lit?'熄灯':'点灯';e.target.setAttribute('aria-pressed',lit)};
// 保持原照片比例，将图片完整放入相框。
const fitPhotos=()=>{for(const plane of clickables){const im=plane.material.map.image;if(!im)continue;const aspect=im.width/im.height;plane.scale.set(Math.min(1,aspect/(.6/.76)),Math.min(1,(.6/.76)/aspect),1)}};loader.manager.onLoad=fitPhotos;fitPhotos();
window.carousel={scene,camera,renderer,renderAt(t){spinning=false;root.rotation.y=t*.2;camera.position.set(Math.sin(.6+t*.035)*12.5,5.7+Math.sin(t*.16)*.5,Math.cos(.6+t*.035)*12.5);camera.lookAt(0,2.65,0);for(const p of photos)p.pivot.rotation.z=Math.sin(t*1.7+p.a)*.035;composer.render()},ready:()=>ready>=12};
